### ISSUE TITLE
Error: Cannot find module 

### ISSUE THREAD

**Issue by mthines** [hex-ci/vscode-stylelint-plus#21]
I keep getting this issue, when working in typescript files.

```
Error: Cannot find module
'/mnt/c/Users/mads/Workspace/platypus/frontend/node_modules/@types/react-
autosuggest/node_modules/stylelint' Require stack: - /home/mthines/.vscode-server/extensions/hex-
ci.stylelint-plus-0.52.10/stylelint-vscode.js - /home/mthines/.vscode-server/extensions/hex-ci.stylelint-
plus-0.52.10/server.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:623:15) at 
Function.Module._load (internal/modules/cjs/loader.js:527:27) at Module.require 
(internal/modules/cjs/loader.js:681:19) at require (internal/modules/cjs/helpers.js:16:16) at 
stylelintVSCode (/home/mthines/.vscode-server/extensions/hex-ci.stylelint-plus-0.52.10/stylelint-
vscode.js:130:18) at validate (/home/mthines/.vscode-server/extensions/hex-ci.stylelint-plus-
0.52.10/server.js:60:26)
```

**Comment by mthines** [comment]
### Vscode settings
```
"stylelint.autoFixOnSave": true,
"stylelint.useLocal": true
```

### `.stylelintrc` settings
```
{
  "plugins": [
    "stylelint-scss"
  ],
  "extends": [
    "stylelint-config-rational-order"
  ],
  "rules": {
    "declaration-empty-line-before": "never",
    "rule-empty-line-before": [
      "always",
      {
        "except": [
          "first-nested",
          "after-single-line-comment"
        ]
      }
    ]
  }
}

```

**Comment by mthines** [comment]
Here's my package.json

```json
    "stylelint": "^13.1.0",
    "stylelint-config-rational-order": "^0.1.2",
    "stylelint-scss": "^3.14.2"
```

**Comment by mthines** [comment]
Oh yeah, that seems to have fixed the issue.
Thank you 💪
