### ISSUE TITLE
Don't fail to load stylelint in projects not using stylelint

### ISSUE THREAD

**Issue by Svish** [hex-ci/vscode-stylelint-plus#25]
I keep getting errors from this plugin when I open up certain projects, and as far as I can see, these projects aren't even using `stylelint` for anything. If they were, clearly the module would be found. And the module _is_ found (i.e. no error) in projects which does use it.

```
Error: Cannot find module 'c:\dev\projects\example\web\node_modules\stylelint'
Require stack: - c:\Users\torber\.vscode\extensions\hex-ci.stylelint-plus-0.52.10\stylelint-vscode.js - c:\Users\torber\.vscode\extensions\hex-ci.stylelint-plus-0.52.10\server.js
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:844:17)
     at Module._load (internal/modules/cjs/loader.js:737:27)
     at Function.Module._load (electron/js2c/asar.js:769:28)
     at Module.require (internal/modules/cjs/loader.js:899:19)
     at require (internal/modules/cjs/helpers.js:74:18)
     at stylelintVSCode (c:\Users\torber\.vscode\extensions\hex-ci.stylelint-plus-0.52.10\stylelint-vscode.js:130:18)
     at validate (c:\Users\torber\.vscode\extensions\hex-ci.stylelint-plus-0.52.10\server.js:60:26)
```

Would be good if this extension handled this better, because the current behavior is confusing and "scary".

(By "scary", I mean that the error looks very serious, and everytime I see it I waste time figuring out what's going on, only to, yet again, find that it's just the stylelint extension again...)

**Comment by miralize** [comment]
Yep it would be good if it didnt throw a warning if a config was not found.
