### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by FDiskas** [hex-ci/vscode-stylelint-plus#29]
Extention: v0.52.12
VScode Version: 1.53.2
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Linux x64 5.8.0-7642-generic
settings
```
  "stylelint.enable": true,
  "stylelint.autoFixOnSave": true,
  "stylelint.useLocal": true,
```
package.json
```
"stylelint": "^13.11.0",
```

.stylelintrc.json
```
{
    "plugins": [
        "stylelint-prettier"
    ],
    "extends": [
        "stylelint-config-standard",
        "stylelint-prettier/recommended"
    ],
    "rules": {
        "prettier/prettier": true,
        "at-rule-no-unknown": [
            true,
            {
                "ignoreAtRules": [
                    "tailwind",
                    "apply",
                    "variants",
                    "responsive",
                    "screen"
                ]
            }
        ]
    }
}
```

Error:
```
Error: Cannot find module '/home/fdisk/Projects/***/node_modules/@types/react/node_modules/stylelint'
Require stack: 
- /home/fdisk/.vscode/extensions/hex-ci.stylelint-plus-0.52.12/stylelint-vscode.js 
- /home/fdisk/.vscode/extensions/hex-ci.stylelint-plus-0.52.12/server.js at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1019:15) at Module._load (internal/modules/cjs/loader.js:895:27) at Function.f._load (electron/js2c/asar_bundle.js:5:12738) at Module.require (internal/modules/cjs/loader.js:1079:19) at require (internal/modules/cjs/helpers.js:72:18) at stylelintVSCode (/home/fdisk/.vscode/extensions/hex-ci.stylelint-plus-0.52.12/stylelint-vscode.js:130:18) at validate (/home/fdisk/.vscode/extensions/hex-ci.stylelint-plus-0.52.12/server.js:60:26)
```

When I hit CTRL and mouse ower any attribute I get such message.
But main functionality like autofix on save is working. See video

Workaround:
turn of useLocal in setings.

Possible problem:
https://github.com/hex-ci/vscode-stylelint-plus/blob/4d3520fe05a78d50152c68b744a4393a4deed38d/server.js#L53

![deepin-screen-recorder_Select area_20210301173730](https://user-images.githubusercontent.com/468006/109520542-05359900-7ab5-11eb-9690-497b154188c8.gif)

**Comment by FDiskas** [comment]
thank you
